[package]
name = "hulk-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Lowering from HULK AST to bytecode IR."

[dependencies]
hulk-ast      = { workspace = true }
hulk-semantic = { workspace = true }
