[package]
name = "hulk-semantic"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Semantic analysis, symbol table, and type checking for HULK."

[dependencies]
hulk-ast = { workspace = true }
thiserror = { workspace = true }
